TelemetryHub: telemetry::ProtoAdapter Class Reference
telemetry::ProtoAdapter Class Reference
Adapter for converting between C++ structs and Protobuf messages.
#include <proto_adapter.h>
Public Types
using TelemetrySampleProto = telemetry::TelemetrySample
Type alias for Protobuf telemetry message (from telemetry.pb.h).
using CppSample = TelemetrySampleCpp
Type alias for C++ telemetry struct.
Static Public Member Functions
static TelemetrySampleProto toProto (const CppSample &sample)
Convert C++ struct to Protobuf message.
static CppSample fromProto (const TelemetrySampleProto &proto)
Convert Protobuf message to C++ struct.
static std::string serialize (const CppSample &sample)
Serialize C++ struct to binary Protobuf format.
static std::optional< CppSample > deserialize (const std::string &binary_data)
Deserialize binary Protobuf data to C++ struct.
static size_t serializedSize (const CppSample &sample)
Calculate serialized size without actually serializing.
Detailed Description
Adapter for converting between C++ structs and Protobuf messages.
Provides bidirectional conversion between TelemetrySampleCpp and Protobuf TelemetrySample messages. This enables type-safe serialization with zero-copy performance characteristics.
Key Features:
Zero-copy conversions where possible
Type-safe API (no raw pointers or manual memory management)
Error handling with std::optional for deserialization
Efficient binary serialization (~10x faster than JSON)
Usage Example:
// Create C++ sample
TelemetrySampleCpp sample;
sample.timestamp = std::chrono::system_clock::now();
sample.value = 25.5;
sample.unit = "celsius";
sample.sequence_id = 42;
// Serialize to binary
std::string binary = ProtoAdapter::serialize(sample);
// binary.size() ~= 30 bytes
// Deserialize back
auto deserialized = ProtoAdapter::deserialize(binary);
if (deserialized) {
    std::cout << "Value: " << deserialized->value << std::endl;
}
Thread Safety: All methods are static and thread-safe. No shared state between calls.
Warning
Deserialization may fail if binary data is corrupted. Always check the std::optional return value before accessing the result.
See also
TelemetrySampleCpp
telemetry::TelemetrySample (Protobuf message)
Definition at line 92 of file proto_adapter.h.
Member Typedef Documentation
CppSample
using telemetry::ProtoAdapter::CppSample = TelemetrySampleCpp
Type alias for C++ telemetry struct.
Definition at line 98 of file proto_adapter.h.
TelemetrySampleProto
using telemetry::ProtoAdapter::TelemetrySampleProto = telemetry::TelemetrySample
Type alias for Protobuf telemetry message (from telemetry.pb.h).
Definition at line 95 of file proto_adapter.h.
Member Function Documentation
deserialize()
std::optional< ProtoAdapter::CppSample > telemetry::ProtoAdapter::deserialize (const std::string & binary_data) static
Deserialize binary Protobuf data to C++ struct.
Parameters
binary_data Binary serialized Protobuf message
Returns
std::optional<CppSample> Deserialized sample, or nullopt if parsing fails
Parses binary Protobuf data and converts to C++ struct. Returns nullopt if data is corrupted or not valid Protobuf format.
Error Handling:
Invalid binary data → returns nullopt (does not throw)
Empty string → returns nullopt
Corrupted Protobuf → returns nullopt
Performance:
~350,000 deserializations per second
Faster than JSON parsing (no string conversions)
std::string binary = receiveFromNetwork();
auto sample = ProtoAdapter::deserialize(binary);
if (sample) {
    std::cout << "Temperature: " << sample->value
              << " " << sample->unit << std::endl;
} else {
    std::cerr << "Failed to deserialize telemetry data" << std::endl;
}
Warning
Always check if optional has value before accessing
See also
serialize()
Definition at line 45 of file proto_adapter.cpp.
References fromProto().
fromProto()
ProtoAdapter::CppSample telemetry::ProtoAdapter::fromProto (const TelemetrySampleProto & proto) static
Convert Protobuf message to C++ struct.
Parameters
proto Protobuf telemetry message to convert
Returns
CppSample C++ struct representation
Performs field-by-field copy from Protobuf message to C++ struct. Timestamp is converted from Unix epoch (seconds + nanoseconds) to std::chrono.
Time Complexity: O(1) - constant time conversion Space Complexity: O(1) - no dynamic allocations except string copy
TelemetrySampleProto proto;  // Received from network
proto.set_value(25.5);
proto.set_unit("celsius");
auto sample = ProtoAdapter::fromProto(proto);
// sample.value == 25.5
Note
This method never throws exceptions
See also
toProto()
Definition at line 22 of file proto_adapter.cpp.
References telemetry::TelemetrySampleCpp::sequence_id, telemetry::TelemetrySampleCpp::timestamp, telemetry::TelemetrySampleCpp::unit, and telemetry::TelemetrySampleCpp::value.
Referenced by deserialize().
serialize()
std::string telemetry::ProtoAdapter::serialize (const CppSample & sample) static
Serialize C++ struct to binary Protobuf format.
Parameters
sample C++ telemetry sample to serialize
Returns
std::string Binary serialized data
Converts C++ struct to Protobuf message and serializes to binary format. This is a convenience method combining toProto() + SerializeToString().
Performance:
~408,000 serializations per second
~30 bytes output size (vs 90 bytes JSON)
10x faster than nlohmann::json
TelemetrySampleCpp sample;
sample.timestamp = std::chrono::system_clock::now();
sample.value = 72.5;
sample.unit = "fahrenheit";
std::string binary = ProtoAdapter::serialize(sample);
// Store in Redis, send over network, etc.
Note
Returns empty string if serialization fails (rare)
See also
deserialize()
serializedSize()
Definition at line 37 of file proto_adapter.cpp.
References toProto().
serializedSize()
size_t telemetry::ProtoAdapter::serializedSize (const CppSample & sample) static
Calculate serialized size without actually serializing.
Parameters
sample C++ telemetry sample
Returns
size_t Size of serialized message in bytes
Computes the wire format size of the Protobuf message without performing actual serialization. Useful for:
Pre-allocating buffers
Estimating bandwidth requirements
Performance comparisons (e.g., Protobuf vs JSON)
Typical Sizes:
Minimal sample (empty strings): ~15 bytes
Average sample: ~30 bytes
Large sample (long unit string): ~50 bytes
JSON equivalent: ~90 bytes (3x larger)
TelemetrySampleCpp sample;
sample.unit = "pascals";
size_t size = ProtoAdapter::serializedSize(sample);
std::cout << "Will serialize to " << size << " bytes" << std::endl;
Note
This is an O(1) approximation, not exact wire size
See also
serialize()
Definition at line 54 of file proto_adapter.cpp.
References toProto().
toProto()
ProtoAdapter::TelemetrySampleProto telemetry::ProtoAdapter::toProto (const CppSample & sample) static
Convert C++ struct to Protobuf message.
Parameters
sample C++ telemetry sample to convert
Returns
TelemetrySampleProto Protobuf message representation
Performs field-by-field copy from C++ struct to Protobuf message. Timestamp is converted from std::chrono to Unix epoch (seconds + nanoseconds).
Time Complexity: O(1) - constant time conversion Space Complexity: O(1) - no dynamic allocations except string copy
TelemetrySampleCpp sample;
sample.timestamp = std::chrono::system_clock::now();
sample.value = 42.0;
auto proto = ProtoAdapter::toProto(sample);
// proto.timestamp_sec() contains Unix timestamp
Note
This method never throws exceptions
See also
fromProto()
Definition at line 6 of file proto_adapter.cpp.
References telemetry::TelemetrySampleCpp::sequence_id, telemetry::TelemetrySampleCpp::timestamp, telemetry::TelemetrySampleCpp::unit, and telemetry::TelemetrySampleCpp::value.
Referenced by serialize(), and serializedSize().
The documentation for this class was generated from the following files:
common/include/telemetry_common/proto_adapter.h
common/src/proto_adapter.cpp