TelemetryHub: telemetry_common::Config Class Reference
telemetry_common::Config Class Reference
Simple INI-style configuration parser.
#include <config.h>
Public Member Functions
bool load_from_file (const std::string &filename)
Load configuration from file.
std::string get_string (const std::string &section, const std::string &key, const std::string &default_value="") const
Get string value.
int get_int (const std::string &section, const std::string &key, int default_value=0) const
Get integer value.
bool get_bool (const std::string &section, const std::string &key, bool default_value=false) const
Get boolean value.
double get_double (const std::string &section, const std::string &key, double default_value=0.0) const
Get double value.
bool has_key (const std::string &section, const std::string &key) const
Check if key exists.
Private Attributes
std::map< std::string, std::map< std::string, std::string > > data_
Detailed Description
Simple INI-style configuration parser.
Supports format: [section] key = value
Definition at line 15 of file config.h.
Member Function Documentation
get_bool()
bool telemetry_common::Config::get_bool (const std::string & section, const std::string & key, bool default_value = false) const
Get boolean value.
Definition at line 79 of file config.cpp.
References get_string().
get_double()
double telemetry_common::Config::get_double (const std::string & section, const std::string & key, double default_value = 0.0) const
Get double value.
Definition at line 91 of file config.cpp.
References get_string().
get_int()
int telemetry_common::Config::get_int (const std::string & section, const std::string & key, int default_value = 0) const
Get integer value.
Definition at line 64 of file config.cpp.
References get_string().
get_string()
std::string telemetry_common::Config::get_string (const std::string & section, const std::string & key, const std::string & default_value = "") const
Get string value.
Parameters
section Section name
key Key name
default_value Default if not found
Definition at line 48 of file config.cpp.
References data_.
Referenced by get_bool(), get_double(), and get_int().
has_key()
bool telemetry_common::Config::has_key (const std::string & section, const std::string & key) const
Check if key exists.
Definition at line 106 of file config.cpp.
References data_.
load_from_file()
bool telemetry_common::Config::load_from_file (const std::string & filename)
Load configuration from file.
Definition at line 15 of file config.cpp.
References data_, and telemetry_common::trim().
Member Data Documentation
data_
std::map<std::string, std::map<std::string, std::string> > telemetry_common::Config::data_ private
Definition at line 59 of file config.h.
Referenced by get_string(), has_key(), and load_from_file().
The documentation for this class was generated from the following files:
common/include/telemetry_common/config.h
common/src/config.cpp