TelemetryHub: telemetryhub::Logger Class Reference
telemetryhub::Logger Class Reference
#include <Log.h>
Public Member Functions
void set_level (LogLevel lvl)
LogLevel level () const
bool open_file (const std::string &path)
void log (LogLevel lvl, const char *cat, const std::string &msg)
Static Public Member Functions
static Logger & instance ()
Static Private Member Functions
static const char * lvl_name (LogLevel l)
Private Attributes
std::atomic< int > level_ {(int)LogLevel::Info}
std::mutex mu_
std::FILE * file_ {nullptr}
Detailed Description
Definition at line 13 of file Log.h.
Member Function Documentation
instance()
Logger & telemetryhub::Logger::instance () inline static
Definition at line 15 of file Log.h.
Referenced by telemetryhub::gateway::apply_cfg_if_any(), and main().
level()
LogLevel telemetryhub::Logger::level () const inline
Definition at line 18 of file Log.h.
References level_.
log()
void telemetryhub::Logger::log (LogLevel lvl, const char * cat, const std::string & msg) inline
Definition at line 28 of file Log.h.
References file_, level_, lvl_name(), and mu_.
lvl_name()
const char * telemetryhub::Logger::lvl_name (LogLevel l) inline static private
Definition at line 42 of file Log.h.
References telemetryhub::Debug, telemetryhub::Error, telemetryhub::Info, and telemetryhub::Warn.
Referenced by log().
open_file()
bool telemetryhub::Logger::open_file (const std::string & path) inline
Definition at line 21 of file Log.h.
References file_, and mu_.
set_level()
void telemetryhub::Logger::set_level (LogLevel lvl) inline
Definition at line 17 of file Log.h.
References level_.
Referenced by telemetryhub::gateway::apply_cfg_if_any(), and main().
Member Data Documentation
file_
std::FILE* telemetryhub::Logger::file_ {nullptr} private
Definition at line 54 of file Log.h.
Referenced by log(), and open_file().
level_
std::atomic<int> telemetryhub::Logger::level_ {(int)LogLevel::Info} private
Definition at line 52 of file Log.h.
Referenced by level(), log(), and set_level().
mu_
std::mutex telemetryhub::Logger::mu_ private
Definition at line 53 of file Log.h.
Referenced by log(), and open_file().
The documentation for this class was generated from the following file:
ingestion/gateway/include/telemetryhub/gateway/Log.h