TelemetryHub: telemetry_processing::TaskQueue Class Reference
telemetry_processing::TaskQueue Class Reference
Thread-safe bounded priority queue for task scheduling.
#include <task_queue.h>
Classes
struct TaskComparator
Comparator for priority queue ordering.
Public Member Functions
TaskQueue (size_t max_capacity=10000)
Construct bounded task queue.
~TaskQueue ()
Destructor - automatically unblocks waiting threads.
TaskQueue (const TaskQueue &)=delete
TaskQueue & operator= (const TaskQueue &)=delete
TaskQueue (TaskQueue &&) noexcept=default
TaskQueue & operator= (TaskQueue &&) noexcept=default
bool enqueue (Task task, std::chrono::milliseconds timeout=std::chrono::milliseconds(0))
Enqueue a task with optional timeout.
std::optional< Task > dequeue (std::chrono::milliseconds timeout=std::chrono::milliseconds(0))
Dequeue highest-priority task with optional timeout.
std::optional< Task > peek () const
Peek at highest-priority task without removing.
size_t size () const
Get current number of tasks in queue.
bool empty () const
Check if queue is empty.
bool full () const
Check if queue is at capacity.
size_t capacity () const
Get maximum queue capacity.
void clear ()
Clear all tasks from queue.
nlohmann::json get_stats () const
Get queue statistics.
Private Attributes
std::mutex mutex_
Protects all shared state.
std::condition_variable not_empty_
Signals when task available.
std::condition_variable not_full_
Signals when space available.
std::priority_queue< Task, std::vector< Task >, TaskComparator > queue_
Underlying priority queue.
size_t max_capacity_
Maximum queue size (0 = unbounded).
bool shutdown_ = false
Shutdown flag (unblock threads).
Detailed Description
Thread-safe bounded priority queue for task scheduling.
Implements a producer-consumer pattern with priority scheduling. Multiple producers can enqueue() tasks, multiple consumers can dequeue().
Concurrency Model:
Mutex protects all shared state (queue, size counters)
Condition variables for blocking operations:
not_empty_: Consumers wait when queue empty
not_full_: Producers wait when queue at capacity
Lock guards ensure exception-safe unlocking
Priority Scheduling:
Uses std::priority_queue with custom comparator
Higher priority (lower enum value) processed first
FIFO ordering within same priority (timestamp comparison)
Bounded Capacity:
Prevents unbounded memory growth
Provides backpressure to producers
Configurable max size (default: 10,000 tasks)
Interview Talking Points:
Why bounded? Prevent OOM in high-load scenarios
Why condition variables? Efficient blocking (no busy-wait)
Why FIFO within priority? Fairness + predictable latency
Thread safety patterns: Lock guards, RAII, move semantics
Usage Example:
// Create queue with capacity 1000
TaskQueue queue(1000);
// Producer thread
Task high_priority_task("alert-001", TaskPriority::HIGH);
high_priority_task.payload = {{"alert", "CPU overload"}};
if (queue.enqueue(std::move(high_priority_task), 5000ms)) {
    std::cout << "Task enqueued successfully" << std::endl;
} else {
    std::cerr << "Queue full, task dropped" << std::endl;
}
// Consumer thread
auto task = queue.dequeue(5000ms);
if (task) {
    processTask(*task);
} else {
    std::cout << "Queue empty, no task available" << std::endl;
}
Warning
Not copyable (queue contains unique state)
Note
All methods are thread-safe
See also
Task for task structure
TaskPriority for priority levels
Definition at line 200 of file task_queue.h.
Constructor & Destructor Documentation
TaskQueue() [1/3]
telemetry_processing::TaskQueue::TaskQueue (size_t max_capacity = 10000) explicit
Construct bounded task queue.
Parameters
max_capacity Maximum number of tasks (default: 10,000)
Creates an empty queue with specified capacity. Choose capacity based on:
Expected throughput (events/sec)
Processing latency (ms/task)
Memory constraints (bytes/task)
Capacity Guidelines:
Low throughput (< 100/sec): 1,000 tasks
Medium throughput (< 1k/sec): 10,000 tasks
High throughput (< 10k/sec): 100,000 tasks
Note
Capacity 0 = unbounded (use with caution!)
Definition at line 6 of file task_queue.cpp.
References max_capacity_.
Referenced by operator=(), operator=(), TaskQueue(), and TaskQueue().
~TaskQueue()
telemetry_processing::TaskQueue::~TaskQueue ()
Destructor - automatically unblocks waiting threads.
Sets shutdown flag and notifies all waiting threads. Prevents deadlock if queue destroyed while threads blocked.
Definition at line 10 of file task_queue.cpp.
References mutex_, not_empty_, not_full_, and shutdown_.
TaskQueue() [2/3]
telemetry_processing::TaskQueue::TaskQueue (const TaskQueue &) delete
References TaskQueue().
TaskQueue() [3/3]
telemetry_processing::TaskQueue::TaskQueue (TaskQueue &&) default noexcept
References TaskQueue().
Member Function Documentation
capacity()
size_t telemetry_processing::TaskQueue::capacity () const
Get maximum queue capacity.
Returns
Max capacity (0 = unbounded)
Definition at line 111 of file task_queue.cpp.
References max_capacity_.
Referenced by operator=().
clear()
void telemetry_processing::TaskQueue::clear ()
Clear all tasks from queue.
Removes all tasks and notifies waiting producers. Useful for:
Graceful shutdown
Error recovery
Priority change (flush old tasks)
Time Complexity: O(n) where n = queue size
Warning
All tasks are lost (consider draining first)
Note
Thread-safe operation
Definition at line 115 of file task_queue.cpp.
References mutex_, not_full_, and queue_.
Referenced by operator=().
dequeue()
std::optional< Task > telemetry_processing::TaskQueue::dequeue (std::chrono::milliseconds timeout = std::chrono::milliseconds(0))
Dequeue highest-priority task with optional timeout.
Parameters
timeout Maximum wait time if queue empty (default: 0 = no wait)
Returns
Optional task (nullopt if timeout or shutdown)
Returns highest-priority task (lowest enum value). If queue is empty:
timeout = 0: Returns nullopt immediately
timeout > 0: Waits up to timeout for task
timeout = max: Waits indefinitely
Time Complexity: O(log n) where n = queue size Thread Safety: Fully synchronized
// Non-blocking dequeue
auto task = queue.dequeue();
if (!task) {
    std::cout << "Queue empty" << std::endl;
}
// Blocking dequeue with 5-second timeout
auto task = queue.dequeue(5000ms);
if (task) {
    processTask(*task);
} else {
    std::cout << "No task after 5 seconds" << std::endl;
}
Note
Returns nullopt if queue is shutting down
Definition at line 56 of file task_queue.cpp.
References mutex_, not_empty_, not_full_, queue_, and shutdown_.
Referenced by operator=().
empty()
bool telemetry_processing::TaskQueue::empty () const
Check if queue is empty.
Returns
true if no tasks in queue
Equivalent to size() == 0 but more expressive.
Note
State may change immediately after call
Definition at line 101 of file task_queue.cpp.
References mutex_, and queue_.
Referenced by operator=().
enqueue()
bool telemetry_processing::TaskQueue::enqueue (Task task, std::chrono::milliseconds timeout = std::chrono::milliseconds(0))
Enqueue a task with optional timeout.
Parameters
task Task to enqueue (moved)
timeout Maximum wait time if queue full (default: 0 = no wait)
Returns
true if enqueued, false if timeout or shutdown
If queue is full:
timeout = 0: Returns false immediately
timeout > 0: Waits up to timeout for space
timeout = max: Waits indefinitely
Time Complexity: O(log n) where n = queue size Thread Safety: Fully synchronized (safe from multiple threads)
Task task("task-001", TaskPriority::HIGH);
// Non-blocking enqueue
if (!queue.enqueue(std::move(task))) {
    std::cerr << "Queue full, task dropped" << std::endl;
}
// Blocking enqueue with 5-second timeout
if (!queue.enqueue(std::move(task), 5000ms)) {
    std::cerr << "Queue full after 5 seconds" << std::endl;
}
Warning
Task is moved (do not use after enqueue)
Note
Returns false if queue is shutting down
Definition at line 20 of file task_queue.cpp.
References max_capacity_, mutex_, not_empty_, not_full_, queue_, and shutdown_.
Referenced by operator=().
full()
bool telemetry_processing::TaskQueue::full () const
Check if queue is at capacity.
Returns
true if no space for new tasks
Returns false if capacity = 0 (unbounded queue).
Note
State may change immediately after call
Definition at line 106 of file task_queue.cpp.
References max_capacity_, mutex_, and queue_.
Referenced by operator=().
get_stats()
nlohmann::json telemetry_processing::TaskQueue::get_stats () const
Get queue statistics.
Returns
JSON object with statistics
Returns:
current_size: Number of tasks
capacity: Max capacity
utilization: Percentage full (0-100)
priority_breakdown: Count per priority level
auto stats = queue.get_stats();
std::cout << "Queue utilization: "
          << stats["utilization"] << "%" << std::endl;
Definition at line 127 of file task_queue.cpp.
References max_capacity_, mutex_, and queue_.
Referenced by operator=().
operator=() [1/2]
TaskQueue & telemetry_processing::TaskQueue::operator= (const TaskQueue &) delete
References TaskQueue().
operator=() [2/2]
TaskQueue & telemetry_processing::TaskQueue::operator= (TaskQueue &&) default noexcept
References capacity(), clear(), dequeue(), empty(), enqueue(), full(), get_stats(), peek(), size(), and TaskQueue().
peek()
std::optional< Task > telemetry_processing::TaskQueue::peek () const
Peek at highest-priority task without removing.
Returns
Optional task (nullopt if empty)
View next task without modifying queue. Useful for:
Checking priority before processing
Monitoring queue state
Conditional dequeue logic
Time Complexity: O(1) - constant time
auto next = queue.peek();
if (next && next->priority == TaskPriority::HIGH) {
    // Process high-priority immediately
    auto task = queue.dequeue();
}
Warning
Task reference may become invalid if queue modified
Note
Thread-safe but task may be dequeued by another thread
Definition at line 86 of file task_queue.cpp.
References mutex_, and queue_.
Referenced by operator=().
size()
size_t telemetry_processing::TaskQueue::size () const
Get current number of tasks in queue.
Returns
Size of queue
Time Complexity: O(1) - cached value Thread Safety: Fully synchronized
Note
Size may change immediately after call (concurrent access)
Definition at line 96 of file task_queue.cpp.
References mutex_, and queue_.
Referenced by operator=().
Member Data Documentation
max_capacity_
size_t telemetry_processing::TaskQueue::max_capacity_ private
Maximum queue size (0 = unbounded).
Definition at line 450 of file task_queue.h.
Referenced by capacity(), enqueue(), full(), get_stats(), and TaskQueue().
mutex_
std::mutex telemetry_processing::TaskQueue::mutex_ mutable private
Protects all shared state.
Definition at line 442 of file task_queue.h.
Referenced by clear(), dequeue(), empty(), enqueue(), full(), get_stats(), peek(), size(), and ~TaskQueue().
not_empty_
std::condition_variable telemetry_processing::TaskQueue::not_empty_ private
Signals when task available.
Definition at line 443 of file task_queue.h.
Referenced by dequeue(), enqueue(), and ~TaskQueue().
not_full_
std::condition_variable telemetry_processing::TaskQueue::not_full_ private
Signals when space available.
Definition at line 444 of file task_queue.h.
Referenced by clear(), dequeue(), enqueue(), and ~TaskQueue().
queue_
std::priority_queue<Task, std::vector<Task>, TaskComparator> telemetry_processing::TaskQueue::queue_ private
Underlying priority queue.
Definition at line 448 of file task_queue.h.
Referenced by clear(), dequeue(), empty(), enqueue(), full(), get_stats(), peek(), and size().
shutdown_
bool telemetry_processing::TaskQueue::shutdown_ = false private
Shutdown flag (unblock threads).
Definition at line 451 of file task_queue.h.
Referenced by dequeue(), enqueue(), and ~TaskQueue().
The documentation for this class was generated from the following files:
processing/include/task_queue.h
processing/src/task_queue.cpp