TelemetryHub: telemetryhub::gateway::ThreadPool Class Reference
telemetryhub::gateway::ThreadPool Class Reference
Simple thread pool for processing telemetry samples.
#include <ThreadPool.h>
Classes
struct Metrics
Get metrics for monitoring.
Public Member Functions
ThreadPool (size_t num_threads=0)
Construct thread pool with N worker threads.
~ThreadPool ()
Destructor - waits for all jobs to complete.
ThreadPool (const ThreadPool &)=delete
ThreadPool & operator= (const ThreadPool &)=delete
ThreadPool (ThreadPool &&)=delete
ThreadPool & operator= (ThreadPool &&)=delete
template<typename F, typename... Args>
auto submit (F &&func, Args &&... args) -> std::future< std::invoke_result_t< F, Args... > >
Submit a job to the thread pool.
Metrics get_metrics () const
size_t thread_count () const
Get number of worker threads.
Private Member Functions
void worker_loop ()
Private Attributes
std::vector< std::thread > workers_
std::queue< std::function< void()> > jobs_
std::mutex queue_mutex_
std::condition_variable cv_
std::atomic< bool > stop_ {false}
std::atomic< uint64_t > jobs_processed_ {0}
std::atomic< uint64_t > total_processing_time_us_ {0}
Detailed Description
Simple thread pool for processing telemetry samples.
Features:
Fixed number of worker threads
Job queue with FIFO processing
Metrics: jobs processed, average processing time
Graceful shutdown with job completion
Design considerations:
Reduces thread creation overhead for high-frequency tasks
Limits concurrency for bounded resource usage
Better CPU utilization through worker reuse
Minimal queue latency for telemetry processing workload
Definition at line 30 of file ThreadPool.h.
Constructor & Destructor Documentation
ThreadPool() [1/3]
telemetryhub::gateway::ThreadPool::ThreadPool (size_t num_threads = 0) explicit
Construct thread pool with N worker threads.
Parameters
num_threads Number of worker threads (0 = hardware concurrency)
Definition at line 6 of file ThreadPool.cpp.
References stop_, worker_loop(), and workers_.
Referenced by operator=(), operator=(), ThreadPool(), and ThreadPool().
~ThreadPool()
telemetryhub::gateway::ThreadPool::~ThreadPool ()
Destructor - waits for all jobs to complete.
Definition at line 22 of file ThreadPool.cpp.
References cv_, queue_mutex_, stop_, and workers_.
ThreadPool() [2/3]
telemetryhub::gateway::ThreadPool::ThreadPool (const ThreadPool &) delete
References ThreadPool().
ThreadPool() [3/3]
telemetryhub::gateway::ThreadPool::ThreadPool (ThreadPool &&) delete
References ThreadPool().
Member Function Documentation
get_metrics()
ThreadPool::Metrics telemetryhub::gateway::ThreadPool::get_metrics () const
Definition at line 80 of file ThreadPool.cpp.
References telemetryhub::gateway::ThreadPool::Metrics::avg_processing_ms, jobs_, telemetryhub::gateway::ThreadPool::Metrics::jobs_processed, jobs_processed_, telemetryhub::gateway::ThreadPool::Metrics::jobs_queued, telemetryhub::gateway::ThreadPool::Metrics::num_threads, queue_mutex_, total_processing_time_us_, and workers_.
operator=() [1/2]
ThreadPool & telemetryhub::gateway::ThreadPool::operator= (const ThreadPool &) delete
References ThreadPool().
operator=() [2/2]
ThreadPool & telemetryhub::gateway::ThreadPool::operator= (ThreadPool &&) delete
References ThreadPool().
submit()
template<typename F, typename... Args> auto telemetryhub::gateway::ThreadPool::submit (F && func, Args &&... args)->std::future< std::invoke_result_t< F, Args... > >
Submit a job to the thread pool.
Parameters
job Function to execute
Returns
Future to get result
Example: auto future = pool.submit([](){ return 42; }); int result = future.get();
Definition at line 99 of file ThreadPool.h.
References cv_, jobs_, queue_mutex_, and stop_.
thread_count()
size_t telemetryhub::gateway::ThreadPool::thread_count () const inline
Get number of worker threads.
Definition at line 76 of file ThreadPool.h.
References workers_.
worker_loop()
void telemetryhub::gateway::ThreadPool::worker_loop () private
Definition at line 39 of file ThreadPool.cpp.
References cv_, jobs_, jobs_processed_, queue_mutex_, stop_, and total_processing_time_us_.
Referenced by ThreadPool().
Member Data Documentation
cv_
std::condition_variable telemetryhub::gateway::ThreadPool::cv_ private
Definition at line 87 of file ThreadPool.h.
Referenced by submit(), worker_loop(), and ~ThreadPool().
jobs_
std::queue<std::function<void()> > telemetryhub::gateway::ThreadPool::jobs_ private
Definition at line 85 of file ThreadPool.h.
Referenced by get_metrics(), submit(), and worker_loop().
jobs_processed_
std::atomic<uint64_t> telemetryhub::gateway::ThreadPool::jobs_processed_ {0} private
Definition at line 93 of file ThreadPool.h.
Referenced by get_metrics(), and worker_loop().
queue_mutex_
std::mutex telemetryhub::gateway::ThreadPool::queue_mutex_ mutable private
Definition at line 86 of file ThreadPool.h.
Referenced by get_metrics(), submit(), worker_loop(), and ~ThreadPool().
stop_
std::atomic<bool> telemetryhub::gateway::ThreadPool::stop_ {false} private
Definition at line 90 of file ThreadPool.h.
Referenced by submit(), ThreadPool(), worker_loop(), and ~ThreadPool().
total_processing_time_us_
std::atomic<uint64_t> telemetryhub::gateway::ThreadPool::total_processing_time_us_ {0} private
Definition at line 94 of file ThreadPool.h.
Referenced by get_metrics(), and worker_loop().
workers_
std::vector<std::thread> telemetryhub::gateway::ThreadPool::workers_ private
Definition at line 82 of file ThreadPool.h.
Referenced by get_metrics(), thread_count(), ThreadPool(), and ~ThreadPool().
The documentation for this class was generated from the following files:
ingestion/gateway/include/telemetryhub/gateway/ThreadPool.h
ingestion/gateway/src/ThreadPool.cpp