TelemetryHub: telemetry_common::RedisClient Class Reference
telemetry_common::RedisClient Class Reference
RAII-based Redis client wrapper with connection pooling.
#include <redis_client.h>
Classes
struct ConnectionOptions
Connection options for Redis.
Public Member Functions
RedisClient (const ConnectionOptions &options=ConnectionOptions{})
Construct Redis client with connection options.
~RedisClient ()
Destructor - automatically closes connection.
RedisClient (const RedisClient &)=delete
RedisClient & operator= (const RedisClient &)=delete
RedisClient (RedisClient &&) noexcept
RedisClient & operator= (RedisClient &&) noexcept
bool ping ()
Test connection with PING command.
bool is_connected () const
Check if client is connected.
bool set (const std::string &key, const std::string &value, int ttl_seconds=0)
Set a key-value pair.
std::optional< std::string > get (const std::string &key)
Get value by key.
int del (const std::string &key)
Delete a key.
bool exists (const std::string &key)
Check if key exists.
bool expire (const std::string &key, int seconds)
Set expiration on a key.
int ttl (const std::string &key)
Get time-to-live for a key.
long long lpush (const std::string &key, const std::string &value)
Push element to head of list (left push).
std::optional< std::string > rpop (const std::string &key)
Pop element from tail of list (right pop).
std::optional< std::string > brpop (const std::string &key, int timeout_seconds=0)
Blocking right pop (waits for element).
long long llen (const std::string &key)
Get list length.
std::vector< std::string > lrange (const std::string &key, long long start, long long stop)
Get range of elements from list.
long long sadd (const std::string &key, const std::string &member)
Add member to set.
bool sismember (const std::string &key, const std::string &member)
Check if member exists in set.
long long srem (const std::string &key, const std::string &member)
Remove member from set.
long long zadd (const std::string &key, const std::string &member, double score)
Add member to sorted set with score.
std::optional< std::string > zpopmax (const std::string &key)
Pop member with highest score (max).
long long zcard (const std::string &key)
Get sorted set cardinality (size).
long long incr (const std::string &key)
Atomic increment.
long long decr (const std::string &key)
Atomic decrement.
const ConnectionOptions & get_options () const
Get connection options used.
std::string info ()
Get info about Redis server.
Private Attributes
ConnectionOptions options_
std::unique_ptr< sw::redis::Redis > redis_
Detailed Description
RAII-based Redis client wrapper with connection pooling.
Wraps redis-plus-plus library with TelemetryHub-specific operations. Provides high-level interface for storing and retrieving telemetry data.
Design Decisions:
PIMPL Pattern: Hides redis++ implementation details from clients
Move-Only Semantics: Redis connections cannot be copied (resource ownership)
Exception Safety: All operations provide strong exception guarantee
Connection Pooling: Automatic pool management for concurrent access
Interview Talking Points:
RAII: Why C++ destructors are critical for resource management
PIMPL: Reduces compile-time dependencies, enables ABI stability
Move Semantics: Efficient transfer of ownership (no deep copy)
Connection Pooling: How to handle concurrent database access
Error Handling: std::optional vs exceptions (when to use each)
Thread Safety:
✅ Multiple RedisClient instances: Safe (separate connections)
✅ Single RedisClient with connection pool: Safe (internally synchronized)
❌ Shared RedisClient across threads: Unsafe without external mutex
Usage Example:
// Configure connection
RedisClient::ConnectionOptions opts;
opts.host = "redis.example.com";
opts.port = 6379;
opts.pool_size = 10;  // 10 connections for concurrent access
// Create client (RAII - connection auto-closed on scope exit)
RedisClient client(opts);
// Test connection
if (!client.ping()) {
    throw std::runtime_error("Redis connection failed");
}
// Store telemetry data with 1-hour TTL
std::string json = serializeTelemetry(data);
client.set("telemetry:device123", json, 3600);
// Retrieve data
auto value = client.get("telemetry:device123");
if (value) {
    auto data = deserializeTelemetry(*value);
    processData(data);
}
// Push to queue for processing
client.rpush("processing_queue", json);
// Worker: blocking pop from queue (timeout: 5 seconds)
auto item = client.blpop("processing_queue", 5000);
if (item) {
    processTelemetry(*item);
}
Warning
Do not share RedisClient across threads without synchronization
Note
Connection is automatically closed when object goes out of scope
See also
ConnectionOptions for configuration
ProtoAdapter for efficient serialization
Definition at line 118 of file redis_client.h.
Constructor & Destructor Documentation
RedisClient() [1/3]
telemetry_common::RedisClient::RedisClient (const ConnectionOptions & options = ConnectionOptions{}) explicit
Construct Redis client with connection options.
Parameters
options Connection configuration
Exceptions
std::runtime_error if connection fails
Definition at line 10 of file redis_client.cpp.
References options_, ping(), and redis_.
Referenced by operator=(), operator=(), ping(), RedisClient(), and RedisClient().
~RedisClient()
telemetry_common::RedisClient::~RedisClient () default
Destructor - automatically closes connection.
RedisClient() [2/3]
telemetry_common::RedisClient::RedisClient (const RedisClient &) delete
References RedisClient().
RedisClient() [3/3]
telemetry_common::RedisClient::RedisClient (RedisClient &&) default noexcept
References RedisClient().
Member Function Documentation
brpop()
std::optional< std::string > telemetry_common::RedisClient::brpop (const std::string & key, int timeout_seconds = 0)
Blocking right pop (waits for element).
Parameters
key List key
timeout_seconds Timeout in seconds (0 = block indefinitely)
Returns
Value if available within timeout, std::nullopt otherwise
Interview note: BRPOP blocks worker thread until task available, more efficient than polling RPOP in loop
Definition at line 164 of file redis_client.cpp.
References redis_.
Referenced by operator=().
decr()
long long telemetry_common::RedisClient::decr (const std::string & key)
Atomic decrement.
Parameters
key The key
Returns
New value after decrement
Definition at line 291 of file redis_client.cpp.
References redis_.
Referenced by operator=().
del()
int telemetry_common::RedisClient::del (const std::string & key)
Delete a key.
Parameters
key The key to delete
Returns
Number of keys deleted (0 or 1)
Definition at line 96 of file redis_client.cpp.
References redis_.
Referenced by operator=().
exists()
bool telemetry_common::RedisClient::exists (const std::string & key)
Check if key exists.
Parameters
key The key
Returns
true if key exists
Definition at line 106 of file redis_client.cpp.
References redis_.
Referenced by operator=().
expire()
bool telemetry_common::RedisClient::expire (const std::string & key, int seconds)
Set expiration on a key.
Parameters
key The key
seconds TTL in seconds
Returns
true if successful
Definition at line 116 of file redis_client.cpp.
References redis_.
Referenced by operator=().
get()
std::optional< std::string > telemetry_common::RedisClient::get (const std::string & key)
Get value by key.
Parameters
key The key
Returns
Value if exists, std::nullopt otherwise
Definition at line 82 of file redis_client.cpp.
References redis_.
Referenced by operator=().
get_options()
const ConnectionOptions & telemetry_common::RedisClient::get_options () const inline
Get connection options used.
Definition at line 339 of file redis_client.h.
References get_options(), and options_.
Referenced by get_options().
incr()
long long telemetry_common::RedisClient::incr (const std::string & key)
Atomic increment.
Parameters
key The key
Returns
New value after increment
Definition at line 281 of file redis_client.cpp.
References redis_.
Referenced by operator=().
info()
std::string telemetry_common::RedisClient::info ()
Get info about Redis server.
Returns
Server info string
Definition at line 303 of file redis_client.cpp.
References redis_.
is_connected()
bool telemetry_common::RedisClient::is_connected () const
Check if client is connected.
Definition at line 61 of file redis_client.cpp.
References redis_.
Referenced by operator=().
llen()
long long telemetry_common::RedisClient::llen (const std::string & key)
Get list length.
Parameters
key List key
Returns
Number of elements in list
Definition at line 188 of file redis_client.cpp.
References redis_.
Referenced by operator=().
lpush()
long long telemetry_common::RedisClient::lpush (const std::string & key, const std::string & value)
Push element to head of list (left push).
Parameters
key List key
value Value to push
Returns
Length of list after push
Interview note: LPUSH is O(1), perfect for producer side of queue
Definition at line 140 of file redis_client.cpp.
References redis_.
Referenced by operator=().
lrange()
std::vector< std::string > telemetry_common::RedisClient::lrange (const std::string & key, long long start, long long stop)
Get range of elements from list.
Parameters
key List key
start Start index (0-based)
stop Stop index (-1 = end)
Returns
Vector of elements
Definition at line 198 of file redis_client.cpp.
References redis_.
Referenced by operator=().
operator=() [1/2]
RedisClient & telemetry_common::RedisClient::operator= (const RedisClient &) delete
References RedisClient().
operator=() [2/2]
RedisClient & telemetry_common::RedisClient::operator= (RedisClient &&) default noexcept
References brpop(), decr(), del(), exists(), expire(), get(), incr(), is_connected(), llen(), lpush(), lrange(), ping(), RedisClient(), rpop(), sadd(), set(), sismember(), srem(), ttl(), zadd(), zcard(), and zpopmax().
ping()
bool telemetry_common::RedisClient::ping ()
Test connection with PING command.
Returns
true if connection is alive
Definition at line 50 of file redis_client.cpp.
References ping(), redis_, and RedisClient().
Referenced by operator=(), ping(), and RedisClient().
rpop()
std::optional< std::string > telemetry_common::RedisClient::rpop (const std::string & key)
Pop element from tail of list (right pop).
Parameters
key List key
Returns
Value if list not empty, std::nullopt otherwise
Interview note: RPOP is O(1), perfect for consumer side of queue Combined with LPUSH creates FIFO queue
Definition at line 150 of file redis_client.cpp.
References redis_.
Referenced by operator=().
sadd()
long long telemetry_common::RedisClient::sadd (const std::string & key, const std::string & member)
Add member to set.
Parameters
key Set key
member Member to add
Returns
Number of members added (0 if already exists, 1 if new)
Definition at line 212 of file redis_client.cpp.
References redis_.
Referenced by operator=().
set()
bool telemetry_common::RedisClient::set (const std::string & key, const std::string & value, int ttl_seconds = 0)
Set a key-value pair.
Parameters
key The key
value The value
ttl_seconds Time-to-live in seconds (0 = no expiration)
Returns
true if successful
Definition at line 67 of file redis_client.cpp.
References redis_, and ttl().
Referenced by operator=().
sismember()
bool telemetry_common::RedisClient::sismember (const std::string & key, const std::string & member)
Check if member exists in set.
Parameters
key Set key
member Member to check
Returns
true if member exists
Definition at line 222 of file redis_client.cpp.
References redis_.
Referenced by operator=().
srem()
long long telemetry_common::RedisClient::srem (const std::string & key, const std::string & member)
Remove member from set.
Parameters
key Set key
member Member to remove
Returns
Number of members removed
Definition at line 232 of file redis_client.cpp.
References redis_.
Referenced by operator=().
ttl()
int telemetry_common::RedisClient::ttl (const std::string & key)
Get time-to-live for a key.
Parameters
key The key
Returns
TTL in seconds, -1 if no expiration, -2 if key doesn't exist
Definition at line 126 of file redis_client.cpp.
References redis_.
Referenced by operator=(), and set().
zadd()
long long telemetry_common::RedisClient::zadd (const std::string & key, const std::string & member, double score)
Add member to sorted set with score.
Parameters
key Sorted set key
member Member to add
score Score for ordering (higher = higher priority)
Returns
Number of members added
Interview note: Sorted sets enable priority queue implementation. Score can represent priority level or timestamp.
Definition at line 244 of file redis_client.cpp.
References redis_.
Referenced by operator=().
zcard()
long long telemetry_common::RedisClient::zcard (const std::string & key)
Get sorted set cardinality (size).
Parameters
key Sorted set key
Returns
Number of members
Definition at line 269 of file redis_client.cpp.
References redis_.
Referenced by operator=().
zpopmax()
std::optional< std::string > telemetry_common::RedisClient::zpopmax (const std::string & key)
Pop member with highest score (max).
Parameters
key Sorted set key
Returns
Member if exists, std::nullopt otherwise
Interview note: ZPOPMAX pops highest priority task first
Definition at line 254 of file redis_client.cpp.
References redis_.
Referenced by operator=().
Member Data Documentation
options_
ConnectionOptions telemetry_common::RedisClient::options_ private
Definition at line 348 of file redis_client.h.
Referenced by get_options(), and RedisClient().
redis_
std::unique_ptr<sw::redis::Redis> telemetry_common::RedisClient::redis_ private
Definition at line 349 of file redis_client.h.
Referenced by brpop(), decr(), del(), exists(), expire(), get(), incr(), info(), is_connected(), llen(), lpush(), lrange(), ping(), RedisClient(), rpop(), sadd(), set(), sismember(), srem(), ttl(), zadd(), zcard(), and zpopmax().
The documentation for this class was generated from the following files:
common/include/telemetry_common/redis_client.h
common/src/redis_client.cpp