TelemetryHub: ingestion/gateway/src/main_gateway.cpp File Reference
main_gateway.cpp File Reference
#include "telemetryhub/gateway/GatewayCore.h"
#include "telemetryhub/gateway/Config.h"
#include "telemetryhub/device/DeviceUtils.h"
#include "telemetryhub/Version.h"
#include "telemetryhub/gateway/Log.h"
#include <chrono>
#include <iostream>
#include <thread>
#include <csignal>
#include <atomic>
Classes
class GatewayCore
Namespaces
namespace telemetryhub
namespace telemetryhub::gateway
Functions
static void on_sigint (int)
static telemetryhub::LogLevel parse_level (std::string_view s)
int telemetryhub::gateway::run_http_server (unsigned short port)
int telemetryhub::gateway::run_http_server_with_config (unsigned short port, const telemetryhub::gateway::AppConfig &cfg)
int main (int argc, char *argv[])
Variables
static std::atomic< bool > g_stop {false}
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 35 of file main_gateway.cpp.
References g_stop, telemetryhub::Logger::instance(), telemetryhub::gateway::load_config(), telemetryhub::gateway::AppConfig::log_level, on_sigint(), parse_level(), telemetryhub::gateway::run_http_server(), telemetryhub::gateway::run_http_server_with_config(), telemetryhub::Logger::set_level(), TELEMETRYHUB_LOG, TELEMETRYHUB_LOGD, TELEMETRYHUB_LOGI, TELEMETRYHUB_LOGW, and telemetryhub::Trace.
on_sigint()
void on_sigint (int) static
Definition at line 19 of file main_gateway.cpp.
References g_stop.
Referenced by main().
parse_level()
telemetryhub::LogLevel parse_level (std::string_view s) static
Definition at line 21 of file main_gateway.cpp.
References telemetryhub::Debug, telemetryhub::Error, telemetryhub::Info, telemetryhub::Trace, and telemetryhub::Warn.
Referenced by telemetryhub::gateway::load_config(), and main().
Variable Documentation
g_stop
std::atomic<bool> g_stop {false} static
Definition at line 18 of file main_gateway.cpp.
Referenced by main(), and on_sigint().