TelemetryHub: telemetry_processor Namespace Reference
telemetry_processor Namespace Reference
Classes
class RedisClient
Redis client wrapper for DistQueue.
struct Task
Core Task data structure.
class TelemetryHandler
Telemetry-specific task handler for TelemetryTaskProcessor.
Enumerations
enum class Priority { HIGH = 0 , NORMAL = 1 , LOW = 2 }
Task priority levels Higher priority tasks are processed first.
enum class TaskStatus {
PENDING , RUNNING , COMPLETED , FAILED ,
CANCELLED
}
Task execution status.
Functions
std::string generate_uuid ()
Generate a UUID v4 string.
std::string priority_to_string (Priority p)
Convert Priority to string.
std::string status_to_string (TaskStatus s)
Convert TaskStatus to string.
Enumeration Type Documentation
Priority
enum class telemetry_processor::Priority strong
Task priority levels Higher priority tasks are processed first.
Enumerator
HIGH
NORMAL
LOW
Definition at line 13 of file Task.h.
TaskStatus
enum class telemetry_processor::TaskStatus strong
Task execution status.
Enumerator
PENDING
RUNNING
COMPLETED
FAILED
CANCELLED
Definition at line 22 of file Task.h.
Function Documentation
generate_uuid()
std::string telemetry_processor::generate_uuid ()
Generate a UUID v4 string.
Returns
UUID string in format: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Definition at line 8 of file Task.cpp.
Referenced by telemetry_processor::Task::create().
priority_to_string()
std::string telemetry_processor::priority_to_string (Priority p)
Convert Priority to string.
Definition at line 45 of file Task.cpp.
References HIGH, LOW, and NORMAL.
Referenced by main().
status_to_string()
std::string telemetry_processor::status_to_string (TaskStatus s)
Convert TaskStatus to string.
Definition at line 54 of file Task.cpp.
References CANCELLED, COMPLETED, FAILED, PENDING, and RUNNING.
Referenced by main().