TelemetryHub: telemetryhub::gateway Namespace Reference
telemetryhub::gateway Namespace Reference
Classes
struct AppConfig
class GatewayCore
class ICloudClient
class RedisPublisher
Redis publisher for TelemetryHub-TelemetryTaskProcessor integration.
class RestCloudClient
class TelemetryQueue
class ThreadPool
Simple thread pool for processing telemetry samples.
Functions
bool load_config (const std::string &path, AppConfig &out)
static std::string json_status ()
static void apply_cfg_if_any (const telemetryhub::gateway::AppConfig *cfg)
int run_http_server (unsigned short port)
int run_http_server_with_config (unsigned short port, const telemetryhub::gateway::AppConfig &cfg)
Variables
static std::shared_ptr< GatewayCore > g_gateway
static std::once_flag g_init_flag
Function Documentation
apply_cfg_if_any()
void telemetryhub::gateway::apply_cfg_if_any (const telemetryhub::gateway::AppConfig * cfg) static
Definition at line 49 of file http_server.cpp.
References g_gateway, telemetryhub::Logger::instance(), telemetryhub::gateway::AppConfig::log_level, telemetryhub::gateway::AppConfig::queue_size, telemetryhub::gateway::AppConfig::sampling_interval, and telemetryhub::Logger::set_level().
Referenced by run_http_server_with_config().
json_status()
std::string telemetryhub::gateway::json_status () static
Definition at line 21 of file http_server.cpp.
References g_gateway.
Referenced by run_http_server().
load_config()
bool telemetryhub::gateway::load_config (const std::string & path, AppConfig & out)
Definition at line 27 of file Config.cpp.
References telemetryhub::gateway::AppConfig::log_level, parse_level(), telemetryhub::gateway::AppConfig::queue_size, and telemetryhub::gateway::AppConfig::sampling_interval.
Referenced by main().
run_http_server()
int telemetryhub::gateway::run_http_server (unsigned short port)
Definition at line 57 of file http_server.cpp.
References httplib::Request::body, g_gateway, g_init_flag, httplib::Server::Get(), json_status(), httplib::Response::set_content(), httplib::Response::status, and TELEMETRYHUB_LOGI.
Referenced by main(), and run_http_server_with_config().
run_http_server_with_config()
int telemetryhub::gateway::run_http_server_with_config (unsigned short port, const telemetryhub::gateway::AppConfig & cfg)
Definition at line 176 of file http_server.cpp.
References apply_cfg_if_any(), g_gateway, g_init_flag, and run_http_server().
Referenced by main().
Variable Documentation
g_gateway
std::shared_ptr<GatewayCore> telemetryhub::gateway::g_gateway static
Definition at line 18 of file http_server.cpp.
Referenced by apply_cfg_if_any(), json_status(), run_http_server(), and run_http_server_with_config().
g_init_flag
std::once_flag telemetryhub::gateway::g_init_flag static
Definition at line 19 of file http_server.cpp.
Referenced by run_http_server(), and run_http_server_with_config().